// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/accountant-crm/go-backend/internal/handlers"
	"github.com/google/uuid"
)

type AIConversation struct {
	ID             string       `json:"id"`
	ConversationID string       `json:"conversation_id"`
	UserID         uuid.UUID    `json:"user_id"`
	TenantID       *uuid.UUID   `json:"tenant_id,omitempty"`
	Messages       []*AIMessage `json:"messages"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

type AIMessage struct {
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	Timestamp time.Time `json:"timestamp"`
	Metadata  JSON      `json:"metadata,omitempty"`
}

type AnomalyItem struct {
	Type        string    `json:"type"`
	EntityType  string    `json:"entity_type"`
	EntityID    uuid.UUID `json:"entity_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Severity    string    `json:"severity"`
	DetectedAt  time.Time `json:"detected_at"`
	ClientName  *string   `json:"client_name,omitempty"`
}

type ClientConnection struct {
	Edges      []*ClientEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"page_info"`
	TotalCount int           `json:"total_count"`
}

type ClientEdge struct {
	Cursor string           `json:"cursor"`
	Node   *handlers.Client `json:"node"`
}

type ClientFilter struct {
	Status             *ClientStatus `json:"status,omitempty"`
	Search             *string       `json:"search,omitempty"`
	AssignedTo         *uuid.UUID    `json:"assigned_to,omitempty"`
	HasOverdueServices *bool         `json:"has_overdue_services,omitempty"`
	RiskScoreMin       *int          `json:"risk_score_min,omitempty"`
	RiskScoreMax       *int          `json:"risk_score_max,omitempty"`
}

type Dashboard struct {
	Stats          *handlers.DashboardStats `json:"stats"`
	UrgentItems    []*UrgentItem            `json:"urgent_items"`
	Deadlines      []*DeadlineItem          `json:"deadlines"`
	RecentActivity []*handlers.ActivityItem `json:"recent_activity"`
	Kanban         *KanbanBoard             `json:"kanban"`
}

type DeadlineItem struct {
	ServiceID     uuid.UUID       `json:"service_id"`
	ServiceName   string          `json:"service_name"`
	ClientID      uuid.UUID       `json:"client_id"`
	ClientName    string          `json:"client_name"`
	Deadline      time.Time       `json:"deadline"`
	DaysRemaining int             `json:"days_remaining"`
	Status        ServiceStatus   `json:"status"`
	Priority      ServicePriority `json:"priority"`
	DocsProgress  string          `json:"docs_progress"`
}

type DocumentConnection struct {
	Edges      []*DocumentEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"page_info"`
	TotalCount int             `json:"total_count"`
}

type DocumentEdge struct {
	Cursor string             `json:"cursor"`
	Node   *handlers.Document `json:"node"`
}

type DocumentFilter struct {
	ClientID       *uuid.UUID      `json:"client_id,omitempty"`
	ServiceID      *uuid.UUID      `json:"service_id,omitempty"`
	Status         *DocumentStatus `json:"status,omitempty"`
	DocumentTypeID *uuid.UUID      `json:"document_type_id,omitempty"`
	UploadedAfter  *time.Time      `json:"uploaded_after,omitempty"`
	UploadedBefore *time.Time      `json:"uploaded_before,omitempty"`
}

type EmailThread struct {
	ID            uuid.UUID         `json:"id"`
	TenantID      uuid.UUID         `json:"tenant_id"`
	ClientID      *uuid.UUID        `json:"client_id,omitempty"`
	Subject       string            `json:"subject"`
	LastMessageAt time.Time         `json:"last_message_at"`
	MessageCount  int               `json:"message_count"`
	CreatedAt     time.Time         `json:"created_at"`
	Emails        []*handlers.Email `json:"emails"`
	Client        *handlers.Client  `json:"client,omitempty"`
}

type KanbanBoard struct {
	NotStarted   []*KanbanService `json:"not_started"`
	InProgress   []*KanbanService `json:"in_progress"`
	AwaitingInfo []*KanbanService `json:"awaiting_info"`
	UnderReview  []*KanbanService `json:"under_review"`
	Completed    []*KanbanService `json:"completed"`
}

type KanbanService struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	ClientID     uuid.UUID       `json:"client_id"`
	ClientName   string          `json:"client_name"`
	Priority     ServicePriority `json:"priority"`
	Deadline     *time.Time      `json:"deadline,omitempty"`
	DocsProgress string          `json:"docs_progress"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"has_next_page"`
	HasPreviousPage bool    `json:"has_previous_page"`
	StartCursor     *string `json:"start_cursor,omitempty"`
	EndCursor       *string `json:"end_cursor,omitempty"`
}

type Query struct {
}

type RiskFactor struct {
	Factor      string `json:"factor"`
	Severity    string `json:"severity"`
	Description string `json:"description"`
}

type SearchResult struct {
	ID          uuid.UUID `json:"id"`
	Type        string    `json:"type"`
	Title       string    `json:"title"`
	Subtitle    *string   `json:"subtitle,omitempty"`
	Description *string   `json:"description,omitempty"`
	Highlight   *string   `json:"highlight,omitempty"`
	URL         string    `json:"url"`
}

type SearchResults struct {
	Clients    []*SearchResult `json:"clients"`
	Documents  []*SearchResult `json:"documents"`
	Services   []*SearchResult `json:"services"`
	Emails     []*SearchResult `json:"emails"`
	TotalCount int             `json:"total_count"`
}

type ServiceConnection struct {
	Edges      []*ServiceEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"page_info"`
	TotalCount int            `json:"total_count"`
}

type ServiceEdge struct {
	Cursor string            `json:"cursor"`
	Node   *handlers.Service `json:"node"`
}

type ServiceFilter struct {
	ClientID       *uuid.UUID       `json:"client_id,omitempty"`
	Status         *ServiceStatus   `json:"status,omitempty"`
	Priority       *ServicePriority `json:"priority,omitempty"`
	ServiceTypeID  *uuid.UUID       `json:"service_type_id,omitempty"`
	AssignedTo     *uuid.UUID       `json:"assigned_to,omitempty"`
	DeadlineBefore *time.Time       `json:"deadline_before,omitempty"`
	DeadlineAfter  *time.Time       `json:"deadline_after,omitempty"`
}

type TroublemakerClient struct {
	ClientID           uuid.UUID     `json:"client_id"`
	ClientName         string        `json:"client_name"`
	CompanyName        string        `json:"company_name"`
	RiskScore          int           `json:"risk_score"`
	RiskLevel          string        `json:"risk_level"`
	RiskFactors        []*RiskFactor `json:"risk_factors"`
	RecommendedActions []string      `json:"recommended_actions"`
	LastContactAt      *time.Time    `json:"last_contact_at,omitempty"`
	OverdueServices    int           `json:"overdue_services"`
	PendingDocuments   int           `json:"pending_documents"`
}

type UrgentItem struct {
	Type        string     `json:"type"`
	EntityID    uuid.UUID  `json:"entity_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	DueAt       *time.Time `json:"due_at,omitempty"`
	Priority    string     `json:"priority"`
	ClientName  *string    `json:"client_name,omitempty"`
}

type ClientStatus string

const (
	ClientStatusActive   ClientStatus = "ACTIVE"
	ClientStatusInactive ClientStatus = "INACTIVE"
	ClientStatusArchived ClientStatus = "ARCHIVED"
	ClientStatusProspect ClientStatus = "PROSPECT"
)

var AllClientStatus = []ClientStatus{
	ClientStatusActive,
	ClientStatusInactive,
	ClientStatusArchived,
	ClientStatusProspect,
}

func (e ClientStatus) IsValid() bool {
	switch e {
	case ClientStatusActive, ClientStatusInactive, ClientStatusArchived, ClientStatusProspect:
		return true
	}
	return false
}

func (e ClientStatus) String() string {
	return string(e)
}

func (e *ClientStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClientStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClientStatus", str)
	}
	return nil
}

func (e ClientStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DocumentStatus string

const (
	DocumentStatusRequested   DocumentStatus = "REQUESTED"
	DocumentStatusUploaded    DocumentStatus = "UPLOADED"
	DocumentStatusUnderReview DocumentStatus = "UNDER_REVIEW"
	DocumentStatusApproved    DocumentStatus = "APPROVED"
	DocumentStatusRejected    DocumentStatus = "REJECTED"
	DocumentStatusExpired     DocumentStatus = "EXPIRED"
)

var AllDocumentStatus = []DocumentStatus{
	DocumentStatusRequested,
	DocumentStatusUploaded,
	DocumentStatusUnderReview,
	DocumentStatusApproved,
	DocumentStatusRejected,
	DocumentStatusExpired,
}

func (e DocumentStatus) IsValid() bool {
	switch e {
	case DocumentStatusRequested, DocumentStatusUploaded, DocumentStatusUnderReview, DocumentStatusApproved, DocumentStatusRejected, DocumentStatusExpired:
		return true
	}
	return false
}

func (e DocumentStatus) String() string {
	return string(e)
}

func (e *DocumentStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocumentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocumentStatus", str)
	}
	return nil
}

func (e DocumentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EmailDirection string

const (
	EmailDirectionInbound  EmailDirection = "INBOUND"
	EmailDirectionOutbound EmailDirection = "OUTBOUND"
)

var AllEmailDirection = []EmailDirection{
	EmailDirectionInbound,
	EmailDirectionOutbound,
}

func (e EmailDirection) IsValid() bool {
	switch e {
	case EmailDirectionInbound, EmailDirectionOutbound:
		return true
	}
	return false
}

func (e EmailDirection) String() string {
	return string(e)
}

func (e *EmailDirection) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EmailDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EmailDirection", str)
	}
	return nil
}

func (e EmailDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EmailSentiment string

const (
	EmailSentimentPositive EmailSentiment = "POSITIVE"
	EmailSentimentNeutral  EmailSentiment = "NEUTRAL"
	EmailSentimentNegative EmailSentiment = "NEGATIVE"
	EmailSentimentUrgent   EmailSentiment = "URGENT"
)

var AllEmailSentiment = []EmailSentiment{
	EmailSentimentPositive,
	EmailSentimentNeutral,
	EmailSentimentNegative,
	EmailSentimentUrgent,
}

func (e EmailSentiment) IsValid() bool {
	switch e {
	case EmailSentimentPositive, EmailSentimentNeutral, EmailSentimentNegative, EmailSentimentUrgent:
		return true
	}
	return false
}

func (e EmailSentiment) String() string {
	return string(e)
}

func (e *EmailSentiment) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EmailSentiment(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EmailSentiment", str)
	}
	return nil
}

func (e EmailSentiment) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EmailStatus string

const (
	EmailStatusDraft     EmailStatus = "DRAFT"
	EmailStatusQueued    EmailStatus = "QUEUED"
	EmailStatusSent      EmailStatus = "SENT"
	EmailStatusDelivered EmailStatus = "DELIVERED"
	EmailStatusBounced   EmailStatus = "BOUNCED"
	EmailStatusFailed    EmailStatus = "FAILED"
)

var AllEmailStatus = []EmailStatus{
	EmailStatusDraft,
	EmailStatusQueued,
	EmailStatusSent,
	EmailStatusDelivered,
	EmailStatusBounced,
	EmailStatusFailed,
}

func (e EmailStatus) IsValid() bool {
	switch e {
	case EmailStatusDraft, EmailStatusQueued, EmailStatusSent, EmailStatusDelivered, EmailStatusBounced, EmailStatusFailed:
		return true
	}
	return false
}

func (e EmailStatus) String() string {
	return string(e)
}

func (e *EmailStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EmailStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EmailStatus", str)
	}
	return nil
}

func (e EmailStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ServicePriority string

const (
	ServicePriorityLow    ServicePriority = "LOW"
	ServicePriorityMedium ServicePriority = "MEDIUM"
	ServicePriorityHigh   ServicePriority = "HIGH"
	ServicePriorityUrgent ServicePriority = "URGENT"
)

var AllServicePriority = []ServicePriority{
	ServicePriorityLow,
	ServicePriorityMedium,
	ServicePriorityHigh,
	ServicePriorityUrgent,
}

func (e ServicePriority) IsValid() bool {
	switch e {
	case ServicePriorityLow, ServicePriorityMedium, ServicePriorityHigh, ServicePriorityUrgent:
		return true
	}
	return false
}

func (e ServicePriority) String() string {
	return string(e)
}

func (e *ServicePriority) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServicePriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServicePriority", str)
	}
	return nil
}

func (e ServicePriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ServiceStatus string

const (
	ServiceStatusNotStarted   ServiceStatus = "NOT_STARTED"
	ServiceStatusInProgress   ServiceStatus = "IN_PROGRESS"
	ServiceStatusAwaitingInfo ServiceStatus = "AWAITING_INFO"
	ServiceStatusUnderReview  ServiceStatus = "UNDER_REVIEW"
	ServiceStatusCompleted    ServiceStatus = "COMPLETED"
	ServiceStatusOnHold       ServiceStatus = "ON_HOLD"
	ServiceStatusCancelled    ServiceStatus = "CANCELLED"
)

var AllServiceStatus = []ServiceStatus{
	ServiceStatusNotStarted,
	ServiceStatusInProgress,
	ServiceStatusAwaitingInfo,
	ServiceStatusUnderReview,
	ServiceStatusCompleted,
	ServiceStatusOnHold,
	ServiceStatusCancelled,
}

func (e ServiceStatus) IsValid() bool {
	switch e {
	case ServiceStatusNotStarted, ServiceStatusInProgress, ServiceStatusAwaitingInfo, ServiceStatusUnderReview, ServiceStatusCompleted, ServiceStatusOnHold, ServiceStatusCancelled:
		return true
	}
	return false
}

func (e ServiceStatus) String() string {
	return string(e)
}

func (e *ServiceStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceStatus", str)
	}
	return nil
}

func (e ServiceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
