package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"encoding/base64"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"

	"github.com/accountant-crm/go-backend/internal/graphql/model"
	"github.com/accountant-crm/go-backend/internal/handlers"
	"github.com/accountant-crm/go-backend/internal/middleware"
)

// =============================================================================
// Helper Functions
// =============================================================================

// statusToClientStatus converts database status string to GraphQL enum
func statusToClientStatus(status string) model.ClientStatus {
	switch strings.ToLower(status) {
	case "active":
		return model.ClientStatusActive
	case "inactive":
		return model.ClientStatusInactive
	case "archived":
		return model.ClientStatusArchived
	case "prospect":
		return model.ClientStatusProspect
	default:
		return model.ClientStatusActive
	}
}

// statusToDocumentStatus converts database status string to GraphQL enum
func statusToDocumentStatus(status string) model.DocumentStatus {
	switch strings.ToLower(status) {
	case "requested":
		return model.DocumentStatusRequested
	case "uploaded":
		return model.DocumentStatusUploaded
	case "under_review", "pending_review":
		return model.DocumentStatusUnderReview
	case "approved":
		return model.DocumentStatusApproved
	case "rejected":
		return model.DocumentStatusRejected
	case "expired":
		return model.DocumentStatusExpired
	default:
		return model.DocumentStatusRequested
	}
}

// statusToServiceStatus converts database status string to GraphQL enum
func statusToServiceStatus(status string) model.ServiceStatus {
	switch strings.ToLower(status) {
	case "not_started":
		return model.ServiceStatusNotStarted
	case "in_progress":
		return model.ServiceStatusInProgress
	case "awaiting_info":
		return model.ServiceStatusAwaitingInfo
	case "under_review":
		return model.ServiceStatusUnderReview
	case "completed":
		return model.ServiceStatusCompleted
	case "on_hold":
		return model.ServiceStatusOnHold
	case "cancelled":
		return model.ServiceStatusCancelled
	default:
		return model.ServiceStatusNotStarted
	}
}

// statusToServicePriority converts database priority string to GraphQL enum
func statusToServicePriority(priority string) model.ServicePriority {
	switch strings.ToLower(priority) {
	case "low":
		return model.ServicePriorityLow
	case "medium":
		return model.ServicePriorityMedium
	case "high":
		return model.ServicePriorityHigh
	case "urgent":
		return model.ServicePriorityUrgent
	default:
		return model.ServicePriorityMedium
	}
}

// statusToEmailDirection converts database direction string to GraphQL enum
func statusToEmailDirection(direction string) model.EmailDirection {
	switch strings.ToLower(direction) {
	case "inbound":
		return model.EmailDirectionInbound
	case "outbound":
		return model.EmailDirectionOutbound
	default:
		return model.EmailDirectionInbound
	}
}

// statusToEmailStatus converts database status string to GraphQL enum
func statusToEmailStatus(status string) model.EmailStatus {
	switch strings.ToLower(status) {
	case "draft":
		return model.EmailStatusDraft
	case "queued":
		return model.EmailStatusQueued
	case "sent":
		return model.EmailStatusSent
	case "delivered":
		return model.EmailStatusDelivered
	case "bounced":
		return model.EmailStatusBounced
	case "failed":
		return model.EmailStatusFailed
	default:
		return model.EmailStatusDraft
	}
}

// statusToEmailSentiment converts database sentiment string to GraphQL enum
func statusToEmailSentiment(sentiment string) *model.EmailSentiment {
	if sentiment == "" {
		return nil
	}
	var s model.EmailSentiment
	switch strings.ToLower(sentiment) {
	case "positive":
		s = model.EmailSentimentPositive
	case "neutral":
		s = model.EmailSentimentNeutral
	case "negative":
		s = model.EmailSentimentNegative
	case "urgent":
		s = model.EmailSentimentUrgent
	default:
		return nil
	}
	return &s
}

// encodeCursor creates a base64 cursor from an ID
func encodeCursor(id uuid.UUID) string {
	return base64.StdEncoding.EncodeToString([]byte(id.String()))
}

// decodeCursor decodes a base64 cursor to an ID
func decodeCursor(cursor string) (uuid.UUID, error) {
	b, err := base64.StdEncoding.DecodeString(cursor)
	if err != nil {
		return uuid.Nil, err
	}
	return uuid.Parse(string(b))
}

// =============================================================================
// Client Resolvers
// =============================================================================

// Status is the resolver for the status field.
func (r *clientResolver) Status(ctx context.Context, obj *handlers.Client) (model.ClientStatus, error) {
	return statusToClientStatus(obj.Status), nil
}

// Documents is the resolver for the documents field.
func (r *clientResolver) Documents(ctx context.Context, obj *handlers.Client, limit *int) ([]*handlers.Document, error) {
	l := 10
	if limit != nil {
		l = *limit
	}

	var documents []*handlers.Document
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT id, tenant_id, client_id, service_id, type_id, name,
			       original_name, file_path, file_size, mime_type, status, ai_summary,
			       uploaded_by, reviewed_by, reviewed_at, expiry_date::text,
			       created_at, updated_at
			FROM documents
			WHERE client_id = $1 AND deleted_at IS NULL
			ORDER BY created_at DESC
			LIMIT $2
		`, obj.ID, l)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var d handlers.Document
			if err := rows.Scan(
				&d.ID, &d.TenantID, &d.ClientID, &d.ServiceID, &d.TypeID, &d.Name,
				&d.OriginalName, &d.FilePath, &d.FileSize, &d.MimeType, &d.Status, &d.AISummary,
				&d.UploadedBy, &d.ReviewedBy, &d.ReviewedAt, &d.ExpiryDate,
				&d.CreatedAt, &d.UpdatedAt,
			); err != nil {
				return err
			}
			documents = append(documents, &d)
		}
		return rows.Err()
	})
	if err != nil {
		log.Error().Err(err).Str("client_id", obj.ID.String()).Msg("Failed to fetch client documents")
		return []*handlers.Document{}, nil
	}
	return documents, nil
}

// Services is the resolver for the services field.
func (r *clientResolver) Services(ctx context.Context, obj *handlers.Client, limit *int) ([]*handlers.Service, error) {
	l := 10
	if limit != nil {
		l = *limit
	}

	var services []*handlers.Service
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT id, tenant_id, client_id, type_id, name,
			       status, priority, deadline::text, completed_at, docs_required, docs_received,
			       staff_id, created_at, updated_at
			FROM services
			WHERE client_id = $1 AND deleted_at IS NULL
			ORDER BY created_at DESC
			LIMIT $2
		`, obj.ID, l)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var s handlers.Service
			if err := rows.Scan(
				&s.ID, &s.TenantID, &s.ClientID, &s.TypeID, &s.Name,
				&s.Status, &s.Priority, &s.Deadline, &s.CompletedAt, &s.DocsRequired, &s.DocsReceived,
				&s.StaffID, &s.CreatedAt, &s.UpdatedAt,
			); err != nil {
				return err
			}
			services = append(services, &s)
		}
		return rows.Err()
	})
	if err != nil {
		log.Error().Err(err).Str("client_id", obj.ID.String()).Msg("Failed to fetch client services")
		return []*handlers.Service{}, nil
	}
	return services, nil
}

// Emails is the resolver for the emails field.
func (r *clientResolver) Emails(ctx context.Context, obj *handlers.Client, limit *int) ([]*handlers.Email, error) {
	l := 10
	if limit != nil {
		l = *limit
	}

	var emails []*handlers.Email
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT id, tenant_id, client_id, staff_id, thread_id, direction,
			       from_email, to_email, subject, body_text, body_html,
			       status, is_read, sentiment, ai_summary, sent_at, created_at
			FROM emails
			WHERE client_id = $1
			ORDER BY COALESCE(sent_at, created_at) DESC
			LIMIT $2
		`, obj.ID, l)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var e handlers.Email
			if err := rows.Scan(
				&e.ID, &e.TenantID, &e.ClientID, &e.StaffID, &e.ThreadID, &e.Direction,
				&e.FromEmail, &e.ToEmail, &e.Subject, &e.BodyText, &e.BodyHTML,
				&e.Status, &e.IsRead, &e.Sentiment, &e.AISummary, &e.SentAt, &e.CreatedAt,
			); err != nil {
				return err
			}
			emails = append(emails, &e)
		}
		return rows.Err()
	})
	if err != nil {
		log.Error().Err(err).Str("client_id", obj.ID.String()).Msg("Failed to fetch client emails")
		return []*handlers.Email{}, nil
	}
	return emails, nil
}

// Notes is the resolver for the notes field.
func (r *clientResolver) Notes(ctx context.Context, obj *handlers.Client, limit *int) ([]*handlers.ClientNote, error) {
	l := 20
	if limit != nil {
		l = *limit
	}

	var notes []*handlers.ClientNote
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT id, tenant_id, client_id, staff_id, note, created_at, updated_at
			FROM client_notes
			WHERE client_id = $1 AND deleted_at IS NULL
			ORDER BY created_at DESC
			LIMIT $2
		`, obj.ID, l)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var n handlers.ClientNote
			if err := rows.Scan(
				&n.ID, &n.TenantID, &n.ClientID, &n.StaffID, &n.Note, &n.CreatedAt, &n.UpdatedAt,
			); err != nil {
				return err
			}
			notes = append(notes, &n)
		}
		return rows.Err()
	})
	if err != nil {
		log.Error().Err(err).Str("client_id", obj.ID.String()).Msg("Failed to fetch client notes")
		return []*handlers.ClientNote{}, nil
	}
	return notes, nil
}

// AssignedStaff is the resolver for the assigned_staff field.
func (r *clientResolver) AssignedStaff(ctx context.Context, obj *handlers.Client) ([]*handlers.User, error) {
	var users []*handlers.User
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT u.id, u.tenant_id, u.name, u.email, u.role, u.status,
			       u.avatar_url, u.phone, u.specialism, u.notes,
			       u.last_login_at, u.created_at, u.updated_at
			FROM users u
			INNER JOIN staff_clients sc ON u.id = sc.staff_id
			WHERE sc.client_id = $1 AND u.deleted_at IS NULL AND sc.deleted_at IS NULL
		`, obj.ID)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var u handlers.User
			var id, tenantID uuid.UUID
			if err := rows.Scan(
				&id, &tenantID, &u.Name, &u.Email, &u.Role, &u.Status,
				&u.AvatarURL, &u.Phone, &u.Specialism, &u.Notes,
				&u.LastLoginAt, &u.CreatedAt, &u.UpdatedAt,
			); err != nil {
				return err
			}
			u.ID = id.String()
			tid := tenantID.String()
			u.TenantID = &tid
			users = append(users, &u)
		}
		return rows.Err()
	})
	if err != nil {
		log.Error().Err(err).Str("client_id", obj.ID.String()).Msg("Failed to fetch assigned staff")
		return []*handlers.User{}, nil
	}
	return users, nil
}

// =============================================================================
// ClientNote Resolvers
// =============================================================================

// Staff is the resolver for the staff field.
func (r *clientNoteResolver) Staff(ctx context.Context, obj *handlers.ClientNote) (*handlers.User, error) {
	loaders := r.GetLoaders(ctx)
	if loaders != nil {
		result := loaders.UserLoader.Load(ctx, obj.StaffID)
		user, err := result()
		if err != nil {
			return nil, err
		}
		if user == nil {
			return nil, nil
		}
		// Convert dataloader.User to handlers.User
		return &handlers.User{
			ID:          user.ID.String(),
			TenantID:    ptrString(user.TenantID.String()),
			Email:       user.Email,
			Name:        user.Name,
			Role:        user.Role,
			AvatarURL:   user.AvatarURL,
			Status:      boolToStatus(user.IsActive),
			LastLoginAt: user.LastLoginAt,
			CreatedAt:   user.CreatedAt,
			UpdatedAt:   user.UpdatedAt,
		}, nil
	}

	// Fallback to direct query
	var u handlers.User
	var id, tenantID uuid.UUID
	err := r.QueryRow(ctx, []interface{}{
		&id, &tenantID, &u.Name, &u.Email, &u.Role, &u.Status,
		&u.AvatarURL, &u.LastLoginAt, &u.CreatedAt, &u.UpdatedAt,
	}, `
		SELECT id, tenant_id, name, email, role, status,
		       avatar_url, last_login_at, created_at, updated_at
		FROM users
		WHERE id = $1 AND deleted_at IS NULL
	`, obj.StaffID)
	if err != nil {
		return nil, nil
	}
	u.ID = id.String()
	tid := tenantID.String()
	u.TenantID = &tid
	return &u, nil
}

func ptrString(s string) *string {
	return &s
}

func boolToStatus(active bool) string {
	if active {
		return "active"
	}
	return "inactive"
}

// =============================================================================
// DashboardStats Resolvers
// =============================================================================

// ActiveServices is the resolver for the active_services field.
func (r *dashboardStatsResolver) ActiveServices(ctx context.Context, obj *handlers.DashboardStats) (int, error) {
	return obj.ServicesInProgress, nil
}

// ServicesAtRisk is the resolver for the services_at_risk field.
func (r *dashboardStatsResolver) ServicesAtRisk(ctx context.Context, obj *handlers.DashboardStats) (int, error) {
	return obj.ServicesOverdue, nil
}

// PendingDocuments is the resolver for the pending_documents field.
func (r *dashboardStatsResolver) PendingDocuments(ctx context.Context, obj *handlers.DashboardStats) (int, error) {
	return obj.DocumentsPending, nil
}

// UnreadEmails is the resolver for the unread_emails field.
func (r *dashboardStatsResolver) UnreadEmails(ctx context.Context, obj *handlers.DashboardStats) (int, error) {
	// Query unread emails count
	var count int
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT COUNT(*) FROM emails
			WHERE is_read = false
		`).Scan(&count)
	})
	if err != nil {
		return 0, nil
	}
	return count, nil
}

// UnreadNotifications is the resolver for the unread_notifications field.
func (r *dashboardStatsResolver) UnreadNotifications(ctx context.Context, obj *handlers.DashboardStats) (int, error) {
	userID := ctx.Value(middleware.AuthUserID)
	if userID == nil {
		return 0, nil
	}

	var count int
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT COUNT(*) FROM notifications
			WHERE user_id = $1 AND is_read = false AND dismissed_at IS NULL
		`, userID).Scan(&count)
	})
	if err != nil {
		return 0, nil
	}
	return count, nil
}

// =============================================================================
// Document Resolvers
// =============================================================================

// FileKey is the resolver for the file_key field.
func (r *documentResolver) FileKey(ctx context.Context, obj *handlers.Document) (*string, error) {
	return obj.FilePath, nil
}

// Status is the resolver for the status field.
func (r *documentResolver) Status(ctx context.Context, obj *handlers.Document) (model.DocumentStatus, error) {
	return statusToDocumentStatus(obj.Status), nil
}

// AiExtracted is the resolver for the ai_extracted field.
// Note: ai_extracted JSON field is not loaded in current handlers.Document struct
func (r *documentResolver) AiExtracted(ctx context.Context, obj *handlers.Document) (model.JSON, error) {
	// Would need to add ai_extracted field to handlers.Document if needed
	return nil, nil
}

// RequestedBy is the resolver for the requested_by field.
// Note: handlers.Document does not have a RequestedBy field; the database schema tracks this via requested_at timestamp
func (r *documentResolver) RequestedBy(ctx context.Context, obj *handlers.Document) (*uuid.UUID, error) {
	// Not tracked in current schema - would need migration to add requested_by column
	return nil, nil
}

// ExpiresAt is the resolver for the expires_at field.
func (r *documentResolver) ExpiresAt(ctx context.Context, obj *handlers.Document) (*time.Time, error) {
	// ExpiryDate is stored as string (DATE format) in database
	if obj.ExpiryDate == nil || *obj.ExpiryDate == "" {
		return nil, nil
	}
	t, err := time.Parse("2006-01-02", *obj.ExpiryDate)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// Client is the resolver for the client field.
func (r *documentResolver) Client(ctx context.Context, obj *handlers.Document) (*handlers.Client, error) {
	if obj.ClientID == nil {
		return nil, nil
	}
	loaders := r.GetLoaders(ctx)
	if loaders != nil {
		result := loaders.ClientLoader.Load(ctx, *obj.ClientID)
		client, err := result()
		if err != nil {
			return nil, err
		}
		if client == nil {
			return nil, nil
		}
		return &handlers.Client{
			ID:                client.ID,
			TenantID:          client.TenantID,
			UserID:            client.UserID,
			CompanyName:       client.CompanyName,
			ContactName:       client.ContactName,
			Email:             client.Email,
			Phone:             client.Phone,
			Address:           client.Address,
			YearEnd:           client.YearEnd,
			UTR:               client.UTR,
			CompanyNumber:     client.CompanyNumber,
			CompanyType:       client.CompanyType,
			IncorporationDate: client.IncorporationDate,
			VATNumber:         client.VATNumber,
			VATQuarter:        client.VATQuarter,
			Status:            client.Status,
			RiskScore:         client.RiskScore,
			EmailStatus:       client.EmailStatus,
			LastContactAt:     client.LastContactAt,
			CreatedAt:         client.CreatedAt,
			UpdatedAt:         client.UpdatedAt,
		}, nil
	}
	return nil, fmt.Errorf("client loader not available")
}

// Service is the resolver for the service field.
func (r *documentResolver) Service(ctx context.Context, obj *handlers.Document) (*handlers.Service, error) {
	if obj.ServiceID == nil {
		return nil, nil
	}
	loaders := r.GetLoaders(ctx)
	if loaders != nil {
		result := loaders.ServiceLoader.Load(ctx, *obj.ServiceID)
		svc, err := result()
		if err != nil {
			return nil, err
		}
		if svc == nil {
			return nil, nil
		}
		clientID := svc.ClientID // Copy to take address
		return &handlers.Service{
			ID:           svc.ID,
			TenantID:     svc.TenantID,
			ClientID:     &clientID,
			TypeID:       svc.TypeID,
			Name:         svc.Name,
			Status:       svc.Status,
			Priority:     svc.Priority,
			Deadline:     svc.Deadline,
			CompletedAt:  svc.CompletedAt,
			DocsRequired: svc.DocsRequired,
			DocsReceived: svc.DocsReceived,
			StaffID:      svc.StaffID,
			CreatedAt:    svc.CreatedAt,
			UpdatedAt:    svc.UpdatedAt,
		}, nil
	}
	return nil, nil
}

// DocumentType is the resolver for the document_type field.
func (r *documentResolver) DocumentType(ctx context.Context, obj *handlers.Document) (*handlers.DocumentType, error) {
	if obj.TypeID == nil {
		return nil, nil
	}

	var dt handlers.DocumentType
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT id, tenant_id, name, description, category, is_active, created_at
			FROM document_types
			WHERE id = $1 AND deleted_at IS NULL
		`, *obj.TypeID).Scan(
			&dt.ID, &dt.TenantID, &dt.Name, &dt.Description, &dt.Category,
			&dt.IsActive, &dt.CreatedAt,
		)
	})
	if err != nil {
		return nil, nil
	}
	return &dt, nil
}

// RequestedByUser is the resolver for the requested_by_user field.
// Note: handlers.Document does not track requested_by user; this would need schema migration
func (r *documentResolver) RequestedByUser(ctx context.Context, obj *handlers.Document) (*handlers.User, error) {
	// Not tracked in current schema
	return nil, nil
}

// UploadedByUser is the resolver for the uploaded_by_user field.
func (r *documentResolver) UploadedByUser(ctx context.Context, obj *handlers.Document) (*handlers.User, error) {
	if obj.UploadedBy == nil {
		return nil, nil
	}
	return r.loadUser(ctx, *obj.UploadedBy)
}

// ReviewedByUser is the resolver for the reviewed_by_user field.
func (r *documentResolver) ReviewedByUser(ctx context.Context, obj *handlers.Document) (*handlers.User, error) {
	if obj.ReviewedBy == nil {
		return nil, nil
	}
	return r.loadUser(ctx, *obj.ReviewedBy)
}

func (r *documentResolver) loadUser(ctx context.Context, userID uuid.UUID) (*handlers.User, error) {
	loaders := r.GetLoaders(ctx)
	if loaders != nil {
		result := loaders.UserLoader.Load(ctx, userID)
		user, err := result()
		if err != nil || user == nil {
			return nil, nil
		}
		return &handlers.User{
			ID:          user.ID.String(),
			TenantID:    ptrString(user.TenantID.String()),
			Email:       user.Email,
			Name:        user.Name,
			Role:        user.Role,
			AvatarURL:   user.AvatarURL,
			Status:      boolToStatus(user.IsActive),
			LastLoginAt: user.LastLoginAt,
			CreatedAt:   user.CreatedAt,
			UpdatedAt:   user.UpdatedAt,
		}, nil
	}
	return nil, nil
}

// =============================================================================
// Email Resolvers
// =============================================================================

// ThreadID is the resolver for the thread_id field.
// Note: handlers.Email stores thread_id as string, but GraphQL schema expects UUID
func (r *emailResolver) ThreadID(ctx context.Context, obj *handlers.Email) (*uuid.UUID, error) {
	if obj.ThreadID == nil || *obj.ThreadID == "" {
		return nil, nil
	}
	// Thread IDs may not always be valid UUIDs (could be email thread IDs)
	// Try to parse as UUID, return nil if not valid
	parsed, err := uuid.Parse(*obj.ThreadID)
	if err != nil {
		return nil, nil
	}
	return &parsed, nil
}

// Direction is the resolver for the direction field.
func (r *emailResolver) Direction(ctx context.Context, obj *handlers.Email) (model.EmailDirection, error) {
	return statusToEmailDirection(obj.Direction), nil
}

// Status is the resolver for the status field.
func (r *emailResolver) Status(ctx context.Context, obj *handlers.Email) (model.EmailStatus, error) {
	return statusToEmailStatus(obj.Status), nil
}

// Sentiment is the resolver for the sentiment field.
func (r *emailResolver) Sentiment(ctx context.Context, obj *handlers.Email) (*model.EmailSentiment, error) {
	if obj.Sentiment == nil {
		return nil, nil
	}
	return statusToEmailSentiment(*obj.Sentiment), nil
}

// AiActionItems is the resolver for the ai_action_items field.
// Note: handlers.Email doesn't have ai_action_items; would need to parse from ai_tags or add field
func (r *emailResolver) AiActionItems(ctx context.Context, obj *handlers.Email) ([]string, error) {
	// Not currently tracked in handlers.Email struct
	return []string{}, nil
}

// ReceivedAt is the resolver for the received_at field.
// Note: emails table doesn't have a received_at column; for inbound emails, created_at serves this purpose
func (r *emailResolver) ReceivedAt(ctx context.Context, obj *handlers.Email) (*time.Time, error) {
	// For inbound emails, use created_at as received_at
	if obj.Direction == "inbound" {
		return &obj.CreatedAt, nil
	}
	return nil, nil
}

// Client is the resolver for the client field.
func (r *emailResolver) Client(ctx context.Context, obj *handlers.Email) (*handlers.Client, error) {
	if obj.ClientID == nil {
		return nil, nil
	}
	loaders := r.GetLoaders(ctx)
	if loaders != nil {
		result := loaders.ClientLoader.Load(ctx, *obj.ClientID)
		client, err := result()
		if err != nil || client == nil {
			return nil, nil
		}
		return &handlers.Client{
			ID:          client.ID,
			TenantID:    client.TenantID,
			CompanyName: client.CompanyName,
			ContactName: client.ContactName,
			Email:       client.Email,
			Status:      client.Status,
			EmailStatus: client.EmailStatus,
			CreatedAt:   client.CreatedAt,
			UpdatedAt:   client.UpdatedAt,
		}, nil
	}
	return nil, nil
}

// Staff is the resolver for the staff field.
func (r *emailResolver) Staff(ctx context.Context, obj *handlers.Email) (*handlers.User, error) {
	if obj.StaffID == nil {
		return nil, nil
	}
	loaders := r.GetLoaders(ctx)
	if loaders != nil {
		result := loaders.UserLoader.Load(ctx, *obj.StaffID)
		user, err := result()
		if err != nil || user == nil {
			return nil, nil
		}
		return &handlers.User{
			ID:        user.ID.String(),
			TenantID:  ptrString(user.TenantID.String()),
			Email:     user.Email,
			Name:      user.Name,
			Role:      user.Role,
			AvatarURL: user.AvatarURL,
			Status:    boolToStatus(user.IsActive),
		}, nil
	}
	return nil, nil
}

// Thread is the resolver for the thread field.
func (r *emailResolver) Thread(ctx context.Context, obj *handlers.Email) (*model.EmailThread, error) {
	if obj.ThreadID == nil {
		return nil, nil
	}

	var thread model.EmailThread
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT id, tenant_id, client_id, subject, last_message_at, message_count, created_at
			FROM email_threads
			WHERE id = $1
		`, *obj.ThreadID).Scan(
			&thread.ID, &thread.TenantID, &thread.ClientID, &thread.Subject,
			&thread.LastMessageAt, &thread.MessageCount, &thread.CreatedAt,
		)
	})
	if err != nil {
		return nil, nil
	}
	return &thread, nil
}

// =============================================================================
// Mutation Resolvers
// =============================================================================

// MarkNotificationRead is the resolver for the mark_notification_read field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, id uuid.UUID) (*handlers.Notification, error) {
	userIDVal := ctx.Value(middleware.AuthUserID)
	if userIDVal == nil {
		return nil, fmt.Errorf("unauthorized")
	}
	userID, ok := userIDVal.(uuid.UUID)
	if !ok {
		return nil, fmt.Errorf("invalid user ID")
	}

	var n handlers.Notification
	var dismissedAt *time.Time
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			UPDATE notifications
			SET is_read = true
			WHERE id = $1 AND user_id = $2 AND dismissed_at IS NULL
			RETURNING id, tenant_id, user_id, type, title, message,
			          entity_type, entity_id, is_read, dismissed_at, created_at
		`, id, userID).Scan(
			&n.ID, &n.TenantID, &n.UserID, &n.Type, &n.Title, &n.Message,
			&n.EntityType, &n.EntityID, &n.IsRead, &dismissedAt, &n.CreatedAt,
		)
	})
	_ = dismissedAt // Silence unused warning
	if err != nil {
		return nil, fmt.Errorf("notification not found")
	}
	return &n, nil
}

// MarkAllNotificationsRead is the resolver for the mark_all_notifications_read field.
func (r *mutationResolver) MarkAllNotificationsRead(ctx context.Context) (int, error) {
	userIDVal := ctx.Value(middleware.AuthUserID)
	if userIDVal == nil {
		return 0, fmt.Errorf("unauthorized")
	}
	userID, ok := userIDVal.(uuid.UUID)
	if !ok {
		return 0, fmt.Errorf("invalid user ID")
	}

	var count int64
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		tag, err := tx.Exec(ctx, `
			UPDATE notifications
			SET is_read = true
			WHERE user_id = $1 AND is_read = false AND dismissed_at IS NULL
		`, userID)
		if err != nil {
			return err
		}
		count = tag.RowsAffected()
		return nil
	})
	if err != nil {
		return 0, err
	}
	return int(count), nil
}

// DismissNotification is the resolver for the dismiss_notification field.
func (r *mutationResolver) DismissNotification(ctx context.Context, id uuid.UUID) (bool, error) {
	userIDVal := ctx.Value(middleware.AuthUserID)
	if userIDVal == nil {
		return false, fmt.Errorf("unauthorized")
	}
	userID, ok := userIDVal.(uuid.UUID)
	if !ok {
		return false, fmt.Errorf("invalid user ID")
	}

	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		now := time.Now()
		_, err := tx.Exec(ctx, `
			UPDATE notifications
			SET dismissed_at = $1
			WHERE id = $2 AND user_id = $3 AND dismissed_at IS NULL
		`, now, id, userID)
		return err
	})
	return err == nil, err
}

// ApproveDocument is the resolver for the approve_document field.
func (r *mutationResolver) ApproveDocument(ctx context.Context, id uuid.UUID, note *string) (*handlers.Document, error) {
	userID := ctx.Value(middleware.AuthUserID)
	if userID == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	var d handlers.Document
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		now := time.Now()
		return tx.QueryRow(ctx, `
			UPDATE documents
			SET status = 'approved', reviewed_by = $1, reviewed_at = $2, updated_at = $2
			WHERE id = $3 AND deleted_at IS NULL
			RETURNING id, tenant_id, client_id, service_id, type_id, name,
			          original_name, file_path, file_size, mime_type, status, ai_summary,
			          uploaded_by, reviewed_by, reviewed_at, expiry_date::text,
			          created_at, updated_at
		`, userID, now, id).Scan(
			&d.ID, &d.TenantID, &d.ClientID, &d.ServiceID, &d.TypeID, &d.Name,
			&d.OriginalName, &d.FilePath, &d.FileSize, &d.MimeType, &d.Status, &d.AISummary,
			&d.UploadedBy, &d.ReviewedBy, &d.ReviewedAt, &d.ExpiryDate,
			&d.CreatedAt, &d.UpdatedAt,
		)
	})
	if err != nil {
		return nil, fmt.Errorf("document not found")
	}
	return &d, nil
}

// RejectDocument is the resolver for the reject_document field.
func (r *mutationResolver) RejectDocument(ctx context.Context, id uuid.UUID, note string) (*handlers.Document, error) {
	userID := ctx.Value(middleware.AuthUserID)
	if userID == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	var d handlers.Document
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		now := time.Now()
		return tx.QueryRow(ctx, `
			UPDATE documents
			SET status = 'rejected', reviewed_by = $1, reviewed_at = $2, review_note = $3, updated_at = $2
			WHERE id = $4 AND deleted_at IS NULL
			RETURNING id, tenant_id, client_id, service_id, type_id, name,
			          original_name, file_path, file_size, mime_type, status, ai_summary,
			          uploaded_by, reviewed_by, reviewed_at, expiry_date::text,
			          created_at, updated_at
		`, userID, now, note, id).Scan(
			&d.ID, &d.TenantID, &d.ClientID, &d.ServiceID, &d.TypeID, &d.Name,
			&d.OriginalName, &d.FilePath, &d.FileSize, &d.MimeType, &d.Status, &d.AISummary,
			&d.UploadedBy, &d.ReviewedBy, &d.ReviewedAt, &d.ExpiryDate,
			&d.CreatedAt, &d.UpdatedAt,
		)
	})
	if err != nil {
		return nil, fmt.Errorf("document not found")
	}
	return &d, nil
}

// UpdateServiceStatus is the resolver for the update_service_status field.
func (r *mutationResolver) UpdateServiceStatus(ctx context.Context, id uuid.UUID, status model.ServiceStatus) (*handlers.Service, error) {
	statusStr := strings.ToLower(string(status))

	var s handlers.Service
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		now := time.Now()
		var completedAt *time.Time
		if status == model.ServiceStatusCompleted {
			completedAt = &now
		}
		return tx.QueryRow(ctx, `
			UPDATE services
			SET status = $1, completed_at = $2, updated_at = $3
			WHERE id = $4 AND deleted_at IS NULL
			RETURNING id, tenant_id, client_id, type_id, name,
			          status, priority, deadline::text, completed_at, docs_required, docs_received,
			          staff_id, created_at, updated_at
		`, statusStr, completedAt, now, id).Scan(
			&s.ID, &s.TenantID, &s.ClientID, &s.TypeID, &s.Name,
			&s.Status, &s.Priority, &s.Deadline, &s.CompletedAt, &s.DocsRequired, &s.DocsReceived,
			&s.StaffID, &s.CreatedAt, &s.UpdatedAt,
		)
	})
	if err != nil {
		return nil, fmt.Errorf("service not found")
	}
	return &s, nil
}

// ClaimEmail is the resolver for the claim_email field.
func (r *mutationResolver) ClaimEmail(ctx context.Context, id uuid.UUID) (*handlers.Email, error) {
	userID := ctx.Value(middleware.AuthUserID)
	if userID == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	var e handlers.Email
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		now := time.Now()
		return tx.QueryRow(ctx, `
			UPDATE emails
			SET staff_id = $1, claimed_at = $2
			WHERE id = $3
			RETURNING id, tenant_id, client_id, staff_id, thread_id, direction,
			          from_email, to_email, subject, body_text, body_html,
			          status, is_read, sentiment, ai_summary, sent_at, created_at
		`, userID, now, id).Scan(
			&e.ID, &e.TenantID, &e.ClientID, &e.StaffID, &e.ThreadID, &e.Direction,
			&e.FromEmail, &e.ToEmail, &e.Subject, &e.BodyText, &e.BodyHTML,
			&e.Status, &e.IsRead, &e.Sentiment, &e.AISummary, &e.SentAt, &e.CreatedAt,
		)
	})
	if err != nil {
		return nil, fmt.Errorf("email not found")
	}
	return &e, nil
}

// UnclaimEmail is the resolver for the unclaim_email field.
func (r *mutationResolver) UnclaimEmail(ctx context.Context, id uuid.UUID) (*handlers.Email, error) {
	var e handlers.Email
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			UPDATE emails
			SET staff_id = NULL, claimed_by = NULL, claimed_at = NULL
			WHERE id = $1
			RETURNING id, tenant_id, client_id, staff_id, thread_id, direction,
			          from_email, to_email, subject, body_text, body_html,
			          status, is_read, sentiment, ai_summary, sent_at, created_at
		`, id).Scan(
			&e.ID, &e.TenantID, &e.ClientID, &e.StaffID, &e.ThreadID, &e.Direction,
			&e.FromEmail, &e.ToEmail, &e.Subject, &e.BodyText, &e.BodyHTML,
			&e.Status, &e.IsRead, &e.Sentiment, &e.AISummary, &e.SentAt, &e.CreatedAt,
		)
	})
	if err != nil {
		return nil, fmt.Errorf("email not found")
	}
	return &e, nil
}

// MarkEmailRead is the resolver for the mark_email_read field.
func (r *mutationResolver) MarkEmailRead(ctx context.Context, id uuid.UUID) (*handlers.Email, error) {
	var e handlers.Email
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			UPDATE emails
			SET is_read = true
			WHERE id = $1
			RETURNING id, tenant_id, client_id, staff_id, thread_id, direction,
			          from_email, to_email, subject, body_text, body_html,
			          status, is_read, sentiment, ai_summary, sent_at, created_at
		`, id).Scan(
			&e.ID, &e.TenantID, &e.ClientID, &e.StaffID, &e.ThreadID, &e.Direction,
			&e.FromEmail, &e.ToEmail, &e.Subject, &e.BodyText, &e.BodyHTML,
			&e.Status, &e.IsRead, &e.Sentiment, &e.AISummary, &e.SentAt, &e.CreatedAt,
		)
	})
	if err != nil {
		return nil, fmt.Errorf("email not found")
	}
	return &e, nil
}

// DeleteAiConversation is the resolver for the delete_ai_conversation field.
func (r *mutationResolver) DeleteAiConversation(ctx context.Context, id string) (bool, error) {
	// AI conversations are stored in MongoDB, proxy to Python AI service
	// For now, return not implemented
	return false, fmt.Errorf("AI conversation deletion requires Python AI service")
}

// =============================================================================
// Notification Resolvers
// =============================================================================

// ReadAt is the resolver for the read_at field.
// Note: handlers.Notification doesn't have ReadAt field; we could query the DB or return nil
func (r *notificationResolver) ReadAt(ctx context.Context, obj *handlers.Notification) (*time.Time, error) {
	// Not tracked in handlers.Notification struct - would need to add field or query DB
	return nil, nil
}

// =============================================================================
// Query Resolvers
// =============================================================================

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context) (*model.Dashboard, error) {
	// Build dashboard stats
	var stats handlers.DashboardStats

	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		// Client stats
		err := tx.QueryRow(ctx, `
			SELECT
				COUNT(*) as total,
				COUNT(*) FILTER (WHERE status = 'active') as active
			FROM clients
			WHERE deleted_at IS NULL
		`).Scan(&stats.TotalClients, &stats.ActiveClients)
		if err != nil {
			return err
		}

		// Service stats
		err = tx.QueryRow(ctx, `
			SELECT
				COUNT(*) as total,
				COUNT(*) FILTER (WHERE status = 'in_progress') as in_progress,
				COUNT(*) FILTER (WHERE status NOT IN ('completed', 'cancelled') AND deadline < CURRENT_DATE) as overdue
			FROM services
			WHERE 1=1
		`).Scan(&stats.TotalServices, &stats.ServicesInProgress, &stats.ServicesOverdue)
		if err != nil {
			return err
		}

		// Document stats
		err = tx.QueryRow(ctx, `
			SELECT
				COUNT(*) as total,
				COUNT(*) FILTER (WHERE status IN ('uploaded', 'pending_review', 'under_review')) as pending
			FROM documents
			WHERE deleted_at IS NULL
		`).Scan(&stats.TotalDocuments, &stats.DocumentsPending)
		if err != nil {
			return err
		}

		return nil
	})
	if err != nil {
		log.Error().Err(err).Msg("Failed to fetch dashboard stats")
	}

	// Build urgent items
	var urgentItems []*model.UrgentItem
	_ = r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT s.id, s.name, c.company_name, s.deadline, s.priority
			FROM services s
			JOIN clients c ON s.client_id = c.id
			WHERE s.status NOT IN ('completed', 'cancelled')
			  AND s.deadline < CURRENT_DATE + INTERVAL '3 days'
			ORDER BY s.deadline ASC
			LIMIT 5
		`)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var item model.UrgentItem
			var deadline *time.Time
			if err := rows.Scan(&item.EntityID, &item.Title, &item.ClientName, &deadline, &item.Priority); err != nil {
				continue
			}
			item.Type = "service"
			item.Description = "Service deadline approaching"
			item.DueAt = deadline
			urgentItems = append(urgentItems, &item)
		}
		return nil
	})

	// Build deadlines
	var deadlines []*model.DeadlineItem
	_ = r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT s.id, s.name, s.client_id, c.company_name, s.deadline, s.status, s.priority,
			       s.docs_received, s.docs_required
			FROM services s
			JOIN clients c ON s.client_id = c.id
			WHERE s.status NOT IN ('completed', 'cancelled')
			  AND s.deadline IS NOT NULL
			  AND s.deadline <= CURRENT_DATE + INTERVAL '14 days'
			ORDER BY s.deadline ASC
			LIMIT 10
		`)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var item model.DeadlineItem
			var status, priority string
			var docsReceived, docsRequired int
			if err := rows.Scan(
				&item.ServiceID, &item.ServiceName, &item.ClientID, &item.ClientName,
				&item.Deadline, &status, &priority, &docsReceived, &docsRequired,
			); err != nil {
				continue
			}
			item.Status = statusToServiceStatus(status)
			item.Priority = statusToServicePriority(priority)
			item.DaysRemaining = int(time.Until(item.Deadline).Hours() / 24)
			if docsRequired > 0 {
				item.DocsProgress = fmt.Sprintf("%d/%d", docsReceived, docsRequired)
			} else {
				item.DocsProgress = "N/A"
			}
			deadlines = append(deadlines, &item)
		}
		return nil
	})

	// Build recent activity
	var activities []*handlers.ActivityItem
	_ = r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT id, action, entity_type, entity_id, metadata->>'description', metadata->>'user_name', created_at
			FROM audit_logs
			ORDER BY created_at DESC
			LIMIT 10
		`)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var item handlers.ActivityItem
			if err := rows.Scan(
				&item.ID, &item.Action, &item.EntityType, &item.EntityID,
				&item.Description, &item.UserName, &item.CreatedAt,
			); err != nil {
				continue
			}
			activities = append(activities, &item)
		}
		return nil
	})

	// Build kanban board
	kanban := &model.KanbanBoard{
		NotStarted:   []*model.KanbanService{},
		InProgress:   []*model.KanbanService{},
		AwaitingInfo: []*model.KanbanService{},
		UnderReview:  []*model.KanbanService{},
		Completed:    []*model.KanbanService{},
	}
	_ = r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT s.id, s.name, s.client_id, c.company_name, s.priority, s.deadline,
			       s.docs_received, s.docs_required, s.status
			FROM services s
			JOIN clients c ON s.client_id = c.id
			WHERE s.status NOT IN ('cancelled')
			ORDER BY s.deadline ASC NULLS LAST
			LIMIT 50
		`)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var item model.KanbanService
			var priority, status string
			var docsReceived, docsRequired int
			if err := rows.Scan(
				&item.ID, &item.Name, &item.ClientID, &item.ClientName,
				&priority, &item.Deadline, &docsReceived, &docsRequired, &status,
			); err != nil {
				continue
			}
			item.Priority = statusToServicePriority(priority)
			if docsRequired > 0 {
				item.DocsProgress = fmt.Sprintf("%d/%d", docsReceived, docsRequired)
			} else {
				item.DocsProgress = "N/A"
			}

			switch strings.ToLower(status) {
			case "not_started":
				kanban.NotStarted = append(kanban.NotStarted, &item)
			case "in_progress":
				kanban.InProgress = append(kanban.InProgress, &item)
			case "awaiting_info":
				kanban.AwaitingInfo = append(kanban.AwaitingInfo, &item)
			case "under_review":
				kanban.UnderReview = append(kanban.UnderReview, &item)
			case "completed":
				kanban.Completed = append(kanban.Completed, &item)
			}
		}
		return nil
	})

	return &model.Dashboard{
		Stats:          &stats,
		UrgentItems:    urgentItems,
		Deadlines:      deadlines,
		RecentActivity: activities,
		Kanban:         kanban,
	}, nil
}

// Client is the resolver for the client field.
func (r *queryResolver) Client(ctx context.Context, id uuid.UUID) (*handlers.Client, error) {
	var c handlers.Client
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT id, tenant_id, user_id, company_name, contact_name, email,
			       phone, address, year_end, utr, company_number, company_type,
			       incorporation_date, vat_number, vat_quarter, status, risk_score,
			       email_status, last_contact_at, created_at, updated_at
			FROM clients
			WHERE id = $1 AND deleted_at IS NULL
		`, id).Scan(
			&c.ID, &c.TenantID, &c.UserID, &c.CompanyName, &c.ContactName, &c.Email,
			&c.Phone, &c.Address, &c.YearEnd, &c.UTR, &c.CompanyNumber, &c.CompanyType,
			&c.IncorporationDate, &c.VATNumber, &c.VATQuarter, &c.Status, &c.RiskScore,
			&c.EmailStatus, &c.LastContactAt, &c.CreatedAt, &c.UpdatedAt,
		)
	})
	if err != nil {
		return nil, nil
	}
	return &c, nil
}

// Clients is the resolver for the clients field.
func (r *queryResolver) Clients(ctx context.Context, filter *model.ClientFilter, first *int, after *string) (*model.ClientConnection, error) {
	limit := 20
	if first != nil {
		limit = *first
	}

	var afterID uuid.UUID
	if after != nil {
		var err error
		afterID, err = decodeCursor(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid cursor")
		}
	}

	var clients []*handlers.Client
	var totalCount int

	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		// Build query with filters
		query := `
			SELECT id, tenant_id, user_id, company_name, contact_name, email,
			       phone, address, year_end, utr, company_number, company_type,
			       incorporation_date, vat_number, vat_quarter, status, risk_score,
			       email_status, last_contact_at, created_at, updated_at
			FROM clients
			WHERE deleted_at IS NULL
		`
		countQuery := `SELECT COUNT(*) FROM clients WHERE deleted_at IS NULL`
		args := []interface{}{}
		argIdx := 1

		if filter != nil {
			if filter.Status != nil {
				query += fmt.Sprintf(" AND status = $%d", argIdx)
				countQuery += fmt.Sprintf(" AND status = $%d", argIdx)
				args = append(args, strings.ToLower(string(*filter.Status)))
				argIdx++
			}
			if filter.Search != nil && *filter.Search != "" {
				query += fmt.Sprintf(" AND (company_name ILIKE $%d OR contact_name ILIKE $%d OR email ILIKE $%d)", argIdx, argIdx, argIdx)
				countQuery += fmt.Sprintf(" AND (company_name ILIKE $%d OR contact_name ILIKE $%d OR email ILIKE $%d)", argIdx, argIdx, argIdx)
				args = append(args, "%"+*filter.Search+"%")
				argIdx++
			}
			if filter.AssignedTo != nil {
				query += fmt.Sprintf(" AND id IN (SELECT client_id FROM staff_clients WHERE staff_id = $%d)", argIdx)
				countQuery += fmt.Sprintf(" AND id IN (SELECT client_id FROM staff_clients WHERE staff_id = $%d)", argIdx)
				args = append(args, *filter.AssignedTo)
				argIdx++
			}
		}

		if afterID != uuid.Nil {
			query += fmt.Sprintf(" AND id > $%d", argIdx)
			args = append(args, afterID)
			argIdx++
		}

		query += " ORDER BY company_name ASC"
		query += fmt.Sprintf(" LIMIT $%d", argIdx)
		args = append(args, limit+1) // Fetch one extra to check if there's a next page

		// Get total count
		countArgs := args[:len(args)-1]
		if afterID != uuid.Nil {
			countArgs = countArgs[:len(countArgs)-1]
		}
		if err := tx.QueryRow(ctx, countQuery, countArgs...).Scan(&totalCount); err != nil {
			return err
		}

		// Get clients
		rows, err := tx.Query(ctx, query, args...)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var c handlers.Client
			if err := rows.Scan(
				&c.ID, &c.TenantID, &c.UserID, &c.CompanyName, &c.ContactName, &c.Email,
				&c.Phone, &c.Address, &c.YearEnd, &c.UTR, &c.CompanyNumber, &c.CompanyType,
				&c.IncorporationDate, &c.VATNumber, &c.VATQuarter, &c.Status, &c.RiskScore,
				&c.EmailStatus, &c.LastContactAt, &c.CreatedAt, &c.UpdatedAt,
			); err != nil {
				return err
			}
			clients = append(clients, &c)
		}
		return rows.Err()
	})
	if err != nil {
		return nil, err
	}

	hasNextPage := len(clients) > limit
	if hasNextPage {
		clients = clients[:limit]
	}

	edges := make([]*model.ClientEdge, len(clients))
	for i, c := range clients {
		edges[i] = &model.ClientEdge{
			Cursor: encodeCursor(c.ID),
			Node:   c,
		}
	}

	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}

	return &model.ClientConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: after != nil,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: totalCount,
	}, nil
}

// Document is the resolver for the document field.
func (r *queryResolver) Document(ctx context.Context, id uuid.UUID) (*handlers.Document, error) {
	var d handlers.Document
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT id, tenant_id, client_id, service_id, type_id, name,
			       original_name, file_path, file_size, mime_type, status, ai_summary,
			       uploaded_by, reviewed_by, reviewed_at, expiry_date::text,
			       created_at, updated_at
			FROM documents
			WHERE id = $1 AND deleted_at IS NULL
		`, id).Scan(
			&d.ID, &d.TenantID, &d.ClientID, &d.ServiceID, &d.TypeID, &d.Name,
			&d.OriginalName, &d.FilePath, &d.FileSize, &d.MimeType, &d.Status, &d.AISummary,
			&d.UploadedBy, &d.ReviewedBy, &d.ReviewedAt, &d.ExpiryDate,
			&d.CreatedAt, &d.UpdatedAt,
		)
	})
	if err != nil {
		return nil, nil
	}
	return &d, nil
}

// Documents is the resolver for the documents field.
func (r *queryResolver) Documents(ctx context.Context, filter *model.DocumentFilter, first *int, after *string) (*model.DocumentConnection, error) {
	limit := 20
	if first != nil {
		limit = *first
	}

	var afterID uuid.UUID
	if after != nil {
		var err error
		afterID, err = decodeCursor(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid cursor")
		}
	}

	var documents []*handlers.Document
	var totalCount int

	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		query := `
			SELECT id, tenant_id, client_id, service_id, type_id, name,
			       original_name, file_path, file_size, mime_type, status, ai_summary,
			       uploaded_by, reviewed_by, reviewed_at, expiry_date::text,
			       created_at, updated_at
			FROM documents
			WHERE deleted_at IS NULL
		`
		countQuery := `SELECT COUNT(*) FROM documents WHERE deleted_at IS NULL`
		args := []interface{}{}
		argIdx := 1

		if filter != nil {
			if filter.ClientID != nil {
				query += fmt.Sprintf(" AND client_id = $%d", argIdx)
				countQuery += fmt.Sprintf(" AND client_id = $%d", argIdx)
				args = append(args, *filter.ClientID)
				argIdx++
			}
			if filter.ServiceID != nil {
				query += fmt.Sprintf(" AND service_id = $%d", argIdx)
				countQuery += fmt.Sprintf(" AND service_id = $%d", argIdx)
				args = append(args, *filter.ServiceID)
				argIdx++
			}
			if filter.Status != nil {
				query += fmt.Sprintf(" AND status = $%d", argIdx)
				countQuery += fmt.Sprintf(" AND status = $%d", argIdx)
				args = append(args, strings.ToLower(string(*filter.Status)))
				argIdx++
			}
		}

		if afterID != uuid.Nil {
			query += fmt.Sprintf(" AND id > $%d", argIdx)
			args = append(args, afterID)
			argIdx++
		}

		query += " ORDER BY created_at DESC"
		query += fmt.Sprintf(" LIMIT $%d", argIdx)
		args = append(args, limit+1)

		countArgs := args[:len(args)-1]
		if afterID != uuid.Nil {
			countArgs = countArgs[:len(countArgs)-1]
		}
		if err := tx.QueryRow(ctx, countQuery, countArgs...).Scan(&totalCount); err != nil {
			return err
		}

		rows, err := tx.Query(ctx, query, args...)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var d handlers.Document
			if err := rows.Scan(
				&d.ID, &d.TenantID, &d.ClientID, &d.ServiceID, &d.TypeID, &d.Name,
				&d.OriginalName, &d.FilePath, &d.FileSize, &d.MimeType, &d.Status, &d.AISummary,
				&d.UploadedBy, &d.ReviewedBy, &d.ReviewedAt, &d.ExpiryDate,
				&d.CreatedAt, &d.UpdatedAt,
			); err != nil {
				return err
			}
			documents = append(documents, &d)
		}
		return rows.Err()
	})
	if err != nil {
		return nil, err
	}

	hasNextPage := len(documents) > limit
	if hasNextPage {
		documents = documents[:limit]
	}

	edges := make([]*model.DocumentEdge, len(documents))
	for i, d := range documents {
		edges[i] = &model.DocumentEdge{
			Cursor: encodeCursor(d.ID),
			Node:   d,
		}
	}

	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}

	return &model.DocumentConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: after != nil,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: totalCount,
	}, nil
}

// Service is the resolver for the service field.
func (r *queryResolver) Service(ctx context.Context, id uuid.UUID) (*handlers.Service, error) {
	var s handlers.Service
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT id, tenant_id, client_id, type_id, name,
			       status, priority, deadline::text, completed_at, docs_required, docs_received,
			       staff_id, created_at, updated_at
			FROM services
			WHERE id = $1
		`, id).Scan(
			&s.ID, &s.TenantID, &s.ClientID, &s.TypeID, &s.Name,
			&s.Status, &s.Priority, &s.Deadline, &s.CompletedAt, &s.DocsRequired, &s.DocsReceived,
			&s.StaffID, &s.CreatedAt, &s.UpdatedAt,
		)
	})
	if err != nil {
		return nil, nil
	}
	return &s, nil
}

// Services is the resolver for the services field.
func (r *queryResolver) Services(ctx context.Context, filter *model.ServiceFilter, first *int, after *string) (*model.ServiceConnection, error) {
	limit := 20
	if first != nil {
		limit = *first
	}

	var afterID uuid.UUID
	if after != nil {
		var err error
		afterID, err = decodeCursor(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid cursor")
		}
	}

	var services []*handlers.Service
	var totalCount int

	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		query := `
			SELECT id, tenant_id, client_id, type_id, name,
			       status, priority, deadline::text, completed_at, docs_required, docs_received,
			       staff_id, created_at, updated_at
			FROM services
			WHERE 1=1
		`
		countQuery := `SELECT COUNT(*) FROM services WHERE 1=1`
		args := []interface{}{}
		argIdx := 1

		if filter != nil {
			if filter.ClientID != nil {
				query += fmt.Sprintf(" AND client_id = $%d", argIdx)
				countQuery += fmt.Sprintf(" AND client_id = $%d", argIdx)
				args = append(args, *filter.ClientID)
				argIdx++
			}
			if filter.Status != nil {
				query += fmt.Sprintf(" AND status = $%d", argIdx)
				countQuery += fmt.Sprintf(" AND status = $%d", argIdx)
				args = append(args, strings.ToLower(string(*filter.Status)))
				argIdx++
			}
			if filter.Priority != nil {
				query += fmt.Sprintf(" AND priority = $%d", argIdx)
				countQuery += fmt.Sprintf(" AND priority = $%d", argIdx)
				args = append(args, strings.ToLower(string(*filter.Priority)))
				argIdx++
			}
			if filter.AssignedTo != nil {
				query += fmt.Sprintf(" AND staff_id = $%d", argIdx)
				countQuery += fmt.Sprintf(" AND staff_id = $%d", argIdx)
				args = append(args, *filter.AssignedTo)
				argIdx++
			}
		}

		if afterID != uuid.Nil {
			query += fmt.Sprintf(" AND id > $%d", argIdx)
			args = append(args, afterID)
			argIdx++
		}

		query += " ORDER BY deadline ASC NULLS LAST"
		query += fmt.Sprintf(" LIMIT $%d", argIdx)
		args = append(args, limit+1)

		countArgs := args[:len(args)-1]
		if afterID != uuid.Nil {
			countArgs = countArgs[:len(countArgs)-1]
		}
		if err := tx.QueryRow(ctx, countQuery, countArgs...).Scan(&totalCount); err != nil {
			return err
		}

		rows, err := tx.Query(ctx, query, args...)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var s handlers.Service
			if err := rows.Scan(
				&s.ID, &s.TenantID, &s.ClientID, &s.TypeID, &s.Name,
				&s.Status, &s.Priority, &s.Deadline, &s.CompletedAt, &s.DocsRequired, &s.DocsReceived,
				&s.StaffID, &s.CreatedAt, &s.UpdatedAt,
			); err != nil {
				return err
			}
			services = append(services, &s)
		}
		return rows.Err()
	})
	if err != nil {
		return nil, err
	}

	hasNextPage := len(services) > limit
	if hasNextPage {
		services = services[:limit]
	}

	edges := make([]*model.ServiceEdge, len(services))
	for i, s := range services {
		edges[i] = &model.ServiceEdge{
			Cursor: encodeCursor(s.ID),
			Node:   s,
		}
	}

	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}

	return &model.ServiceConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: after != nil,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: totalCount,
	}, nil
}

// Email is the resolver for the email field.
func (r *queryResolver) Email(ctx context.Context, id uuid.UUID) (*handlers.Email, error) {
	var e handlers.Email
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT id, tenant_id, client_id, staff_id, thread_id, direction,
			       from_email, to_email, subject, body_text, body_html,
			       status, is_read, sentiment, ai_summary, sent_at, created_at
			FROM emails
			WHERE id = $1
		`, id).Scan(
			&e.ID, &e.TenantID, &e.ClientID, &e.StaffID, &e.ThreadID, &e.Direction,
			&e.FromEmail, &e.ToEmail, &e.Subject, &e.BodyText, &e.BodyHTML,
			&e.Status, &e.IsRead, &e.Sentiment, &e.AISummary, &e.SentAt, &e.CreatedAt,
		)
	})
	if err != nil {
		return nil, nil
	}
	return &e, nil
}

// EmailThread is the resolver for the email_thread field.
func (r *queryResolver) EmailThread(ctx context.Context, id uuid.UUID) (*model.EmailThread, error) {
	var thread model.EmailThread
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT id, tenant_id, client_id, subject, last_message_at, message_count, created_at
			FROM email_threads
			WHERE id = $1
		`, id).Scan(
			&thread.ID, &thread.TenantID, &thread.ClientID, &thread.Subject,
			&thread.LastMessageAt, &thread.MessageCount, &thread.CreatedAt,
		)
	})
	if err != nil {
		return nil, nil
	}
	return &thread, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, unreadOnly *bool, limit *int) ([]*handlers.Notification, error) {
	userID := ctx.Value(middleware.AuthUserID)
	if userID == nil {
		return []*handlers.Notification{}, nil
	}

	l := 20
	if limit != nil {
		l = *limit
	}

	var notifications []*handlers.Notification
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		query := `
			SELECT id, tenant_id, user_id, type, title, message,
			       entity_type, entity_id, is_read, created_at
			FROM notifications
			WHERE user_id = $1 AND dismissed_at IS NULL
		`
		args := []interface{}{userID}
		argIdx := 2

		if unreadOnly != nil && *unreadOnly {
			query += " AND is_read = false"
		}

		query += " ORDER BY created_at DESC"
		query += fmt.Sprintf(" LIMIT $%d", argIdx)
		args = append(args, l)

		rows, err := tx.Query(ctx, query, args...)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var n handlers.Notification
			if err := rows.Scan(
				&n.ID, &n.TenantID, &n.UserID, &n.Type, &n.Title, &n.Message,
				&n.EntityType, &n.EntityID, &n.IsRead, &n.CreatedAt,
			); err != nil {
				return err
			}
			notifications = append(notifications, &n)
		}
		return rows.Err()
	})
	if err != nil {
		return []*handlers.Notification{}, nil
	}
	return notifications, nil
}

// UnreadNotificationCount is the resolver for the unread_notification_count field.
func (r *queryResolver) UnreadNotificationCount(ctx context.Context) (int, error) {
	userID := ctx.Value(middleware.AuthUserID)
	if userID == nil {
		return 0, nil
	}

	var count int
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT COUNT(*) FROM notifications
			WHERE user_id = $1 AND is_read = false AND dismissed_at IS NULL
		`, userID).Scan(&count)
	})
	if err != nil {
		return 0, nil
	}
	return count, nil
}

// AiConversations is the resolver for the ai_conversations field.
func (r *queryResolver) AiConversations(ctx context.Context, limit *int) ([]*model.AIConversation, error) {
	// AI conversations are stored in MongoDB via Python AI service
	// Return empty for now - would need to proxy to Python AI
	return []*model.AIConversation{}, nil
}

// AiConversation is the resolver for the ai_conversation field.
func (r *queryResolver) AiConversation(ctx context.Context, id string) (*model.AIConversation, error) {
	// AI conversations are stored in MongoDB via Python AI service
	return nil, nil
}

// TroublemakerClients is the resolver for the troublemaker_clients field.
func (r *queryResolver) TroublemakerClients(ctx context.Context, limit *int) ([]*model.TroublemakerClient, error) {
	l := 10
	if limit != nil {
		l = *limit
	}

	var clients []*model.TroublemakerClient
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT c.id, c.contact_name, c.company_name, c.risk_score, c.last_contact_at,
			       (SELECT COUNT(*) FROM services s WHERE s.client_id = c.id AND s.status NOT IN ('completed', 'cancelled') AND s.deadline < CURRENT_DATE) as overdue_services,
			       (SELECT COUNT(*) FROM documents d WHERE d.client_id = c.id AND d.status = 'requested') as pending_documents
			FROM clients c
			WHERE c.risk_score IS NOT NULL AND c.risk_score >= 70 AND c.deleted_at IS NULL
			ORDER BY c.risk_score DESC
			LIMIT $1
		`, l)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var c model.TroublemakerClient
			var riskScore *int
			if err := rows.Scan(
				&c.ClientID, &c.ClientName, &c.CompanyName, &riskScore, &c.LastContactAt,
				&c.OverdueServices, &c.PendingDocuments,
			); err != nil {
				continue
			}
			if riskScore != nil {
				c.RiskScore = *riskScore
				if *riskScore >= 90 {
					c.RiskLevel = "critical"
				} else if *riskScore >= 80 {
					c.RiskLevel = "high"
				} else {
					c.RiskLevel = "medium"
				}
			}
			c.RiskFactors = []*model.RiskFactor{}
			c.RecommendedActions = []string{}
			clients = append(clients, &c)
		}
		return rows.Err()
	})
	if err != nil {
		return []*model.TroublemakerClient{}, nil
	}
	return clients, nil
}

// Anomalies is the resolver for the anomalies field.
func (r *queryResolver) Anomalies(ctx context.Context, limit *int) ([]*model.AnomalyItem, error) {
	// Anomalies would typically come from AI analysis
	// Return empty for now
	return []*model.AnomalyItem{}, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, limit *int) (*model.SearchResults, error) {
	l := 20
	if limit != nil {
		l = *limit
	}
	perType := l / 4

	searchPattern := "%" + query + "%"
	results := &model.SearchResults{
		Clients:    []*model.SearchResult{},
		Documents:  []*model.SearchResult{},
		Services:   []*model.SearchResult{},
		Emails:     []*model.SearchResult{},
		TotalCount: 0,
	}

	_ = r.WithTransaction(ctx, func(tx pgx.Tx) error {
		// Search clients
		rows, err := tx.Query(ctx, `
			SELECT id, company_name, contact_name, email
			FROM clients
			WHERE deleted_at IS NULL AND (
				company_name ILIKE $1 OR contact_name ILIKE $1 OR email ILIKE $1
			)
			LIMIT $2
		`, searchPattern, perType)
		if err == nil {
			defer rows.Close()
			for rows.Next() {
				var r model.SearchResult
				var companyName, contactName, email string
				if err := rows.Scan(&r.ID, &companyName, &contactName, &email); err == nil {
					r.Type = "client"
					r.Title = companyName
					r.Subtitle = &contactName
					r.URL = "/dashboard/clients/" + r.ID.String()
					results.Clients = append(results.Clients, &r)
					results.TotalCount++
				}
			}
		}

		// Search documents
		rows2, err := tx.Query(ctx, `
			SELECT d.id, d.name, d.original_name, c.company_name
			FROM documents d
			LEFT JOIN clients c ON d.client_id = c.id
			WHERE d.deleted_at IS NULL AND (
				d.name ILIKE $1 OR d.original_name ILIKE $1
			)
			LIMIT $2
		`, searchPattern, perType)
		if err == nil {
			defer rows2.Close()
			for rows2.Next() {
				var r model.SearchResult
				var name, origName string
				var clientName *string
				if err := rows2.Scan(&r.ID, &name, &origName, &clientName); err == nil {
					r.Type = "document"
					r.Title = name
					r.Subtitle = clientName
					r.URL = "/dashboard/documents/" + r.ID.String()
					results.Documents = append(results.Documents, &r)
					results.TotalCount++
				}
			}
		}

		// Search services
		rows3, err := tx.Query(ctx, `
			SELECT s.id, s.name, c.company_name
			FROM services s
			LEFT JOIN clients c ON s.client_id = c.id
			WHERE s.name ILIKE $1
			LIMIT $2
		`, searchPattern, perType)
		if err == nil {
			defer rows3.Close()
			for rows3.Next() {
				var r model.SearchResult
				var name string
				var clientName *string
				if err := rows3.Scan(&r.ID, &name, &clientName); err == nil {
					r.Type = "service"
					r.Title = name
					r.Subtitle = clientName
					r.URL = "/dashboard/services/" + r.ID.String()
					results.Services = append(results.Services, &r)
					results.TotalCount++
				}
			}
		}

		// Search emails
		rows4, err := tx.Query(ctx, `
			SELECT id, subject, from_email
			FROM emails
			WHERE subject ILIKE $1 OR from_email ILIKE $1 OR to_email ILIKE $1
			LIMIT $2
		`, searchPattern, perType)
		if err == nil {
			defer rows4.Close()
			for rows4.Next() {
				var r model.SearchResult
				var subject, fromEmail string
				if err := rows4.Scan(&r.ID, &subject, &fromEmail); err == nil {
					r.Type = "email"
					r.Title = subject
					r.Subtitle = &fromEmail
					r.URL = "/dashboard/emails/" + r.ID.String()
					results.Emails = append(results.Emails, &r)
					results.TotalCount++
				}
			}
		}

		return nil
	})

	return results, nil
}

// RecentSearches is the resolver for the recent_searches field.
func (r *queryResolver) RecentSearches(ctx context.Context, limit *int) ([]*model.SearchResult, error) {
	// Would need to track search history in Redis or DB
	return []*model.SearchResult{}, nil
}

// DocumentTypes is the resolver for the document_types field.
func (r *queryResolver) DocumentTypes(ctx context.Context) ([]*handlers.DocumentType, error) {
	var types []*handlers.DocumentType
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT id, tenant_id, name, description, category, is_active, created_at
			FROM document_types
			WHERE is_active = true
			ORDER BY name ASC
		`)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var t handlers.DocumentType
			if err := rows.Scan(
				&t.ID, &t.TenantID, &t.Name, &t.Description, &t.Category,
				&t.IsActive, &t.CreatedAt,
			); err != nil {
				return err
			}
			types = append(types, &t)
		}
		return rows.Err()
	})
	if err != nil {
		return []*handlers.DocumentType{}, nil
	}
	return types, nil
}

// ServiceTypes is the resolver for the service_types field.
func (r *queryResolver) ServiceTypes(ctx context.Context) ([]*handlers.ServiceType, error) {
	var types []*handlers.ServiceType
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT id, tenant_id, name, description, category, default_deadline_days, is_active, created_at
			FROM service_types
			WHERE is_active = true
			ORDER BY name ASC
		`)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var t handlers.ServiceType
			if err := rows.Scan(
				&t.ID, &t.TenantID, &t.Name, &t.Description, &t.Category,
				&t.DefaultDeadlineDays, &t.IsActive, &t.CreatedAt,
			); err != nil {
				return err
			}
			types = append(types, &t)
		}
		return rows.Err()
	})
	if err != nil {
		return []*handlers.ServiceType{}, nil
	}
	return types, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*handlers.User, error) {
	userIDVal := ctx.Value(middleware.AuthUserID)
	if userIDVal == nil {
		return nil, fmt.Errorf("unauthorized: no user in context")
	}
	userID, ok := userIDVal.(uuid.UUID)
	if !ok || userID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized: invalid user ID")
	}

	var id uuid.UUID
	var tenantID *uuid.UUID
	var user handlers.User
	var lastLoginAt *time.Time
	var createdAt, updatedAt time.Time

	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT id, tenant_id, name, email, role, status, avatar_url, phone,
			       specialism, notes, last_login_at, created_at, updated_at
			FROM users
			WHERE id = $1 AND deleted_at IS NULL
		`, userID).Scan(
			&id, &tenantID, &user.Name, &user.Email, &user.Role, &user.Status,
			&user.AvatarURL, &user.Phone, &user.Specialism, &user.Notes,
			&lastLoginAt, &createdAt, &updatedAt,
		)
	})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch user: %w", err)
	}

	user.ID = id.String()
	if tenantID != nil {
		tid := tenantID.String()
		user.TenantID = &tid
	}
	user.LastLoginAt = lastLoginAt
	user.CreatedAt = createdAt
	user.UpdatedAt = updatedAt

	return &user, nil
}

// =============================================================================
// Service Resolvers
// =============================================================================

// ServiceTypeID is the resolver for the service_type_id field.
func (r *serviceResolver) ServiceTypeID(ctx context.Context, obj *handlers.Service) (*uuid.UUID, error) {
	return obj.TypeID, nil
}

// Description is the resolver for the description field.
// Note: services table doesn't have a description column; use completion_notes or name instead
func (r *serviceResolver) Description(ctx context.Context, obj *handlers.Service) (*string, error) {
	return obj.CompletionNotes, nil // Using completion_notes as description fallback
}

// Status is the resolver for the status field.
func (r *serviceResolver) Status(ctx context.Context, obj *handlers.Service) (model.ServiceStatus, error) {
	return statusToServiceStatus(obj.Status), nil
}

// Priority is the resolver for the priority field.
func (r *serviceResolver) Priority(ctx context.Context, obj *handlers.Service) (model.ServicePriority, error) {
	return statusToServicePriority(obj.Priority), nil
}

// Deadline is the resolver for the deadline field.
func (r *serviceResolver) Deadline(ctx context.Context, obj *handlers.Service) (*time.Time, error) {
	if obj.Deadline == nil {
		return nil, nil
	}
	// Parse the date string (format: YYYY-MM-DD)
	t, err := time.Parse("2006-01-02", *obj.Deadline)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// AssignedTo is the resolver for the assigned_to field.
func (r *serviceResolver) AssignedTo(ctx context.Context, obj *handlers.Service) (*uuid.UUID, error) {
	return obj.StaffID, nil
}

// HmrcData is the resolver for the hmrc_data field.
// Note: handlers.Service does not have an HMRCData field; returning nil for now
func (r *serviceResolver) HmrcData(ctx context.Context, obj *handlers.Service) (model.JSON, error) {
	return nil, nil
}

// Client is the resolver for the client field.
func (r *serviceResolver) Client(ctx context.Context, obj *handlers.Service) (*handlers.Client, error) {
	if obj.ClientID == nil {
		return nil, nil
	}
	loaders := r.GetLoaders(ctx)
	if loaders != nil {
		result := loaders.ClientLoader.Load(ctx, *obj.ClientID)
		client, err := result()
		if err != nil || client == nil {
			return nil, nil
		}
		return &handlers.Client{
			ID:          client.ID,
			TenantID:    client.TenantID,
			CompanyName: client.CompanyName,
			ContactName: client.ContactName,
			Email:       client.Email,
			Status:      client.Status,
			EmailStatus: client.EmailStatus,
			CreatedAt:   client.CreatedAt,
			UpdatedAt:   client.UpdatedAt,
		}, nil
	}
	return nil, nil
}

// ServiceType is the resolver for the service_type field.
func (r *serviceResolver) ServiceType(ctx context.Context, obj *handlers.Service) (*handlers.ServiceType, error) {
	if obj.TypeID == nil {
		return nil, nil
	}

	var st handlers.ServiceType
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT id, tenant_id, name, description, category, default_deadline_days, is_active, created_at
			FROM service_types
			WHERE id = $1
		`, *obj.TypeID).Scan(
			&st.ID, &st.TenantID, &st.Name, &st.Description, &st.Category,
			&st.DefaultDeadlineDays, &st.IsActive, &st.CreatedAt,
		)
	})
	if err != nil {
		return nil, nil
	}
	return &st, nil
}

// AssignedUser is the resolver for the assigned_user field.
func (r *serviceResolver) AssignedUser(ctx context.Context, obj *handlers.Service) (*handlers.User, error) {
	if obj.StaffID == nil {
		return nil, nil
	}
	loaders := r.GetLoaders(ctx)
	if loaders != nil {
		result := loaders.UserLoader.Load(ctx, *obj.StaffID)
		user, err := result()
		if err != nil || user == nil {
			return nil, nil
		}
		return &handlers.User{
			ID:        user.ID.String(),
			TenantID:  ptrString(user.TenantID.String()),
			Email:     user.Email,
			Name:      user.Name,
			Role:      user.Role,
			AvatarURL: user.AvatarURL,
			Status:    boolToStatus(user.IsActive),
		}, nil
	}
	return nil, nil
}

// Documents is the resolver for the documents field.
func (r *serviceResolver) Documents(ctx context.Context, obj *handlers.Service, limit *int) ([]*handlers.Document, error) {
	l := 10
	if limit != nil {
		l = *limit
	}

	var documents []*handlers.Document
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT id, tenant_id, client_id, service_id, document_type_id, name,
			       original_name, file_key, file_size, mime_type, status, ai_summary,
			       requested_by, uploaded_by, reviewed_by, reviewed_at, expires_at,
			       created_at, updated_at
			FROM documents
			WHERE service_id = $1 AND deleted_at IS NULL
			ORDER BY created_at DESC
			LIMIT $2
		`, obj.ID, l)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var d handlers.Document
			if err := rows.Scan(
				&d.ID, &d.TenantID, &d.ClientID, &d.ServiceID, &d.TypeID, &d.Name,
				&d.OriginalName, &d.FilePath, &d.FileSize, &d.MimeType, &d.Status, &d.AISummary,
				&d.UploadedBy, &d.ReviewedBy, &d.ReviewedAt, &d.ExpiryDate,
				&d.CreatedAt, &d.UpdatedAt,
			); err != nil {
				return err
			}
			documents = append(documents, &d)
		}
		return rows.Err()
	})
	if err != nil {
		return []*handlers.Document{}, nil
	}
	return documents, nil
}

// =============================================================================
// ServiceType Resolvers
// =============================================================================

// RequiredDocuments is the resolver for the required_documents field.
func (r *serviceTypeResolver) RequiredDocuments(ctx context.Context, obj *handlers.ServiceType) ([]string, error) {
	// Query required documents from service_requirements table
	var docs []string
	err := r.WithTransaction(ctx, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT dt.name
			FROM service_requirements sr
			JOIN document_types dt ON sr.document_type_id = dt.id
			WHERE sr.service_type_id = $1
		`, obj.ID)
		if err != nil {
			return err
		}
		defer rows.Close()

		for rows.Next() {
			var name string
			if err := rows.Scan(&name); err != nil {
				return err
			}
			docs = append(docs, name)
		}
		return rows.Err()
	})
	if err != nil {
		return []string{}, nil
	}
	return docs, nil
}

// =============================================================================
// Subscription Resolvers (Stubs - WebSocket hub handles real-time)
// =============================================================================

// NotificationReceived is the resolver for the notification_received field.
func (r *subscriptionResolver) NotificationReceived(ctx context.Context) (<-chan *handlers.Notification, error) {
	// Subscriptions would connect to WebSocket hub
	// For now, return a channel that never sends (stub)
	ch := make(chan *handlers.Notification)
	return ch, nil
}

// DocumentProcessed is the resolver for the document_processed field.
func (r *subscriptionResolver) DocumentProcessed(ctx context.Context, clientID *uuid.UUID) (<-chan *handlers.Document, error) {
	ch := make(chan *handlers.Document)
	return ch, nil
}

// ServiceAtRisk is the resolver for the service_at_risk field.
func (r *subscriptionResolver) ServiceAtRisk(ctx context.Context) (<-chan *handlers.Service, error) {
	ch := make(chan *handlers.Service)
	return ch, nil
}

// =============================================================================
// User Resolvers
// =============================================================================

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *handlers.User) (uuid.UUID, error) {
	return uuid.Parse(obj.ID)
}

// TenantID is the resolver for the tenant_id field.
func (r *userResolver) TenantID(ctx context.Context, obj *handlers.User) (uuid.UUID, error) {
	if obj.TenantID == nil {
		return uuid.Nil, nil
	}
	return uuid.Parse(*obj.TenantID)
}

// IsActive is the resolver for the is_active field.
func (r *userResolver) IsActive(ctx context.Context, obj *handlers.User) (bool, error) {
	return obj.Status == "active", nil
}

// =============================================================================
// Resolver Type Definitions
// =============================================================================

// Client returns ClientResolver implementation.
func (r *Resolver) Client() ClientResolver { return &clientResolver{r} }

// ClientNote returns ClientNoteResolver implementation.
func (r *Resolver) ClientNote() ClientNoteResolver { return &clientNoteResolver{r} }

// DashboardStats returns DashboardStatsResolver implementation.
func (r *Resolver) DashboardStats() DashboardStatsResolver { return &dashboardStatsResolver{r} }

// Document returns DocumentResolver implementation.
func (r *Resolver) Document() DocumentResolver { return &documentResolver{r} }

// Email returns EmailResolver implementation.
func (r *Resolver) Email() EmailResolver { return &emailResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Notification returns NotificationResolver implementation.
func (r *Resolver) Notification() NotificationResolver { return &notificationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Service returns ServiceResolver implementation.
func (r *Resolver) Service() ServiceResolver { return &serviceResolver{r} }

// ServiceType returns ServiceTypeResolver implementation.
func (r *Resolver) ServiceType() ServiceTypeResolver { return &serviceTypeResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type clientResolver struct{ *Resolver }
type clientNoteResolver struct{ *Resolver }
type dashboardStatsResolver struct{ *Resolver }
type documentResolver struct{ *Resolver }
type emailResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type notificationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type serviceResolver struct{ *Resolver }
type serviceTypeResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
